Repository belf-kr/front-server, pull requests merged in 2021-05, with the labels that each got.

#27 디렉토리 구조설정, recoil
  README.md
  components/Display.tsx
  components/Input.tsx
  components/states.tsx
  hooks/mock
  package-lock.json
  package.json
  pages/_app.tsx
  pages/about.tsx
  pages/api/hello.ts
  pages/home.tsx
  pages/index.tsx
  states/mock
  styles/mock
  utils/mock
Labels: initial setting, structure

#31 오늘 할일 페이지의 컴포넌트 기능 구현
  .babelrc
  README.md
  assets/icons/bell.ts
  assets/icons/bigCheck.ts
  assets/icons/bigDelete.ts
  components/Display.tsx
  components/Input.tsx
  components/NotificationButton/index.tsx
  components/NotificationButton/style.ts
  components/PageTitle/index.tsx
  components/PageTitle/style.ts
  components/PlantingGlass/Component.tsx
  components/PlantingGlass/index.tsx
  components/PlantingGlass/style.ts
  components/TodayTodoItem/index.tsx
  components/TodayTodoItem/style.ts
  components/TodayTodoList/Component.tsx
  components/TodayTodoList/index.tsx
  components/states.tsx
  data/plantingGlass.json
  data/todayTodoList.json
  hooks/mock
  hooks/useClick.ts
  layouts/RepresentativeLayout/ContentsSection/index.tsx
  layouts/RepresentativeLayout/ContentsSection/style.ts
  layouts/RepresentativeLayout/HeaderSection/index.tsx
  layouts/RepresentativeLayout/HeaderSection/style.ts
  layouts/RepresentativeLayout/index.tsx
  layouts/RepresentativeLayout/style.ts
  layouts/TodayLayout/PlantingGlassSection/index.tsx
  layouts/TodayLayout/PlantingGlassSection/style.ts
  layouts/TodayLayout/TodoListSection/index.tsx
  layouts/TodayLayout/TodoListSection/style.ts
  layouts/TodayLayout/index.tsx
  libs/axios/getPlantingGlass.ts
  libs/axios/getTodayTodoList.ts
  libs/type/Icon/index.ts
  libs/type/PlantingGlass/index.ts
  libs/type/TodoTodayItem/indes.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/about.tsx
  pages/index.tsx
  public/favicon.ico
  states/TodayTodoList/index.ts
  states/mock
  states/plantingGlass/index.ts
  styles/GlobalStyle.ts
  styles/Icon.ts
  styles/mock
  theme/common.ts
  theme/darkTheme.ts
  theme/lightTheme.ts
  theme/theme.ts
  utils/mock
Labels: documentation, modify, new feature, structure

#37 v0.1.0
  .babelrc
  README.md
  assets/icons/bell.ts
  assets/icons/bigCheck.ts
  assets/icons/bigDelete.ts
  components/NotificationButton/index.tsx
  components/NotificationButton/style.ts
  components/PageTitle/index.tsx
  components/PageTitle/style.ts
  components/PlantingGlass/Component.tsx
  components/PlantingGlass/index.tsx
  components/PlantingGlass/style.ts
  components/TodayTodoItem/index.tsx
  components/TodayTodoItem/style.ts
  components/TodayTodoList/Component.tsx
  components/TodayTodoList/index.tsx
  data/plantingGlass.json
  data/todayTodoList.json
  hooks/useClick.ts
  layouts/RepresentativeLayout/ContentsSection/index.tsx
  layouts/RepresentativeLayout/ContentsSection/style.ts
  layouts/RepresentativeLayout/HeaderSection/index.tsx
  layouts/RepresentativeLayout/HeaderSection/style.ts
  layouts/RepresentativeLayout/index.tsx
  layouts/RepresentativeLayout/style.ts
  layouts/TodayLayout/PlantingGlassSection/index.tsx
  layouts/TodayLayout/PlantingGlassSection/style.ts
  layouts/TodayLayout/TodoListSection/index.tsx
  layouts/TodayLayout/TodoListSection/style.ts
  layouts/TodayLayout/index.tsx
  libs/axios/getPlantingGlass.ts
  libs/axios/getTodayTodoList.ts
  libs/type/Icon/index.ts
  libs/type/PlantingGlass/index.ts
  libs/type/TodoTodayItem/indes.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/about.tsx
  pages/api/hello.ts
  pages/index.tsx
  public/favicon.ico
  states/TodayTodoList/index.ts
  states/plantingGlass/index.ts
  styles/GlobalStyle.ts
  styles/Icon.ts
  theme/common.ts
  theme/darkTheme.ts
  theme/lightTheme.ts
  theme/theme.ts
Labels: deployment

#40 prod에 정상적으로 배포 되도록 수정 및 배포 상태 개선
  .eslintrc.json
  k8s/prod.yaml
  k8s/qa.yaml
  k8s/test.yaml
  package.json
  pages/_app.tsx
Labels: bug

#41 v0.1.1
  .eslintrc.json
  k8s/prod.yaml
  k8s/qa.yaml
  k8s/test.yaml
  package.json
  pages/_app.tsx
Labels: bug
