Repository belf-kr/front-server, pull requests merged in 2021-12, with the labels that each got.

#96 한일 보기 & 코스 헤더 오류 수정 & Storage Server 요청 방식 변경 & 기존 인증 헤더 방식 변경
  domain/Course/Detail/CourseDetailNavigate/index.tsx
  domain/Course/Detail/Done/DoneItem/index.tsx
  domain/Course/Detail/Done/DoneItem/style.ts
  domain/Course/Detail/Done/DoneList/index.tsx
  domain/Course/Detail/Done/DoneList/style.ts
  domain/Course/Detail/DoneTab/index.tsx
  domain/Course/Detail/TodoItem/index.tsx
  domain/Editer/PostMaster/index.tsx
  domain/Editer/PostMaster/style.ts
  domain/Editer/PostNodeItem/index.tsx
  domain/Editer/PostNodeItem/style.ts
  domain/Editer/PostNodeList/index.tsx
  domain/Editer/PostNodeList/style.ts
  domain/Todo/TodayTodoItem/index.tsx
  libs/course/index.ts
  libs/storage/index.ts
  libs/todo/index.ts
  libs/work-done/index.ts
  package.json
  pages/[userEmail]/[courseId]/done/[doneId]/post/index.tsx
  pages/[userEmail]/[courseId]/index.tsx
  pages/[userEmail]/[courseId]/todo/[todoId]/write/index.tsx
  types/components-type/todo/index.ts
Labels: new feature, modify, deployment

#97 미니 프로필 클릭 시 팝업을 통해 로그아웃, 마이페이지, 설정 메뉴 추가 & 로그인, 로그아웃 오류 수정, next 버전 픽스
  domain/Header/UserProfile/index.tsx
  domain/Header/UserProfile/style.ts
  domain/Header/index.tsx
  domain/Todo/TodayTodoList/index.tsx
  package-lock.json
  package.json
Labels: new feature, modify, deployment

#99 코스, 할일, 한일 삭제 기능 추가 & 스타일 수정
  components/Kebab/index.tsx
  components/Kebab/style.ts
  domain/Course/CoursePinItem/index.tsx
  domain/Course/CoursePinItem/style.ts
  domain/Course/CoursePinList/style.ts
  domain/Course/Detail/Done/DoneItem/index.tsx
  domain/Course/Detail/Done/DoneItem/style.ts
  domain/Course/Detail/TodoItem/index.tsx
  domain/Course/Detail/TodoItem/style.ts
  domain/Todo/TodayTodoItem/index.tsx
  domain/Todo/TodayTodoItem/style.ts
  icons/KebabIcon/index.tsx
  icons/svg/Kebab.svg
  libs/course/index.ts
  libs/todo/index.ts
  libs/work-done/index.ts
  pages/[userEmail]/index.tsx
  types/components-type/kebab/index.ts
Labels: new feature, modify, deployment

#100 Belf 기능 트리거 버튼 추가, Belf 시 적용될 로딩 추가, 기존 회원가입 End Point 변경
  domain/Course/Detail/CourseHeader/BelfLoading/index.tsx
  domain/Course/Detail/CourseHeader/BelfLoading/style.ts
  domain/Course/Detail/CourseHeader/index.tsx
  domain/Course/Detail/CourseHeader/style.ts
  libs/course/index.ts
  libs/oauth/index.ts
Labels: new feature, modify, deployment

#101 유저 세팅 페이지 추가 & 기존 헤더 유저 프로필 메뉴 링크 추가
  domain/Header/UserProfile/index.tsx
  domain/Setting/EditButton/index.tsx
  domain/Setting/EditButton/style.ts
  domain/Setting/SettingMaster/index.tsx
  domain/Setting/SettingMaster/style.ts
  pages/setting/index.tsx
Labels: new feature, modify, deployment

#102 로그인한 사용자와 조회한 사용자 상태 분리, 이외 명확하게 컴포넌트 네이밍, loading 컴포넌트 추가, 퀄리티 개선
  components/AppInit.tsx
  components/Button/index.tsx
  components/Loading/index.tsx
  components/Loading/style.ts
  components/LoadingSpinner/index.tsx
  components/LoginUser.tsx
  components/QueryStringUser.tsx
  domain/Course/CourseList/index.tsx
  domain/Course/CoursePinItem/index.tsx
  domain/Course/CoursePinList/index.tsx
  domain/Course/Detail/CourseDetailNavigate/index.tsx
  domain/Course/Detail/CourseHeader/index.tsx
  domain/Course/Detail/Done/DoneItem/index.tsx
  domain/Course/Detail/TodoItem/index.tsx
  domain/Course/Detail/TodoList/index.tsx
  domain/Editer/EditerMaster/index.tsx
  domain/Header/UserProfile/index.tsx
  domain/HomeIntro/MainIntro/index.tsx
  domain/HomeIntro/MainIntro/style.ts
  domain/Setting/SettingMaster/index.tsx
  domain/Todo/CreateTodo/index.tsx
  domain/Todo/SelectCourse/index.tsx
  domain/Todo/TodayTodoItem/index.tsx
  domain/Todo/TodayTodoList/index.tsx
  domain/UserPage/UserPageNavigate/index.tsx
  domain/UserPage/UserProfile/index.tsx
  pages/[userEmail]/[courseId]/done/[doneId]/post/index.tsx
  pages/[userEmail]/[courseId]/index.tsx
  pages/[userEmail]/[courseId]/todo/[todoId]/write/index.tsx
  pages/[userEmail]/index.tsx
  pages/_app.tsx
  pages/new-todo/index.tsx
  states/app.ts
Labels: modify

#103 Search 페이지 추가 및 Search 기능 추가 & 오늘 할일 스타일 및 코맨트 수정
  domain/Course/SearchCourseItem/index.tsx
  domain/Course/SearchCourseItem/style.ts
  domain/Course/SearchCourseList/index.tsx
  domain/Course/SearchCourseList/style.ts
  domain/Search/SearchTitle/index.tsx
  domain/Search/SearchTitle/style.ts
  domain/SearchInput/index.tsx
  domain/SearchInput/style.ts
  domain/Todo/TodayTodoList/index.tsx
  layouts/SearchLayout/index.tsx
  layouts/SearchLayout/style.ts
  libs/course/index.ts
  pages/search/index.tsx
  types/components-type/course/index.ts
Labels: new feature, modify, deployment

#104 사용자 프로필 사진 업로드, 회원 탈퇴 기능 추가
  components/LoginUser.tsx
  domain/Course/CourseList/index.tsx
  domain/Course/CoursePinList/index.tsx
  domain/Course/Detail/Done/DoneList/index.tsx
  domain/Course/Detail/TodoList/index.tsx
  domain/Header/UserProfile/index.tsx
  domain/Setting/EditButton/style.ts
  domain/Setting/SettingMaster/index.tsx
  domain/Setting/SettingMaster/style.ts
  libs/oauth/index.ts
Labels: new feature

#105 deprecated된 kubectl 명령어 변경, slack slack notification 메시지 표시되도록
  .github/workflows/aks-prod-deploy.yaml
  .github/workflows/aks-qa-deploy.yaml
  .github/workflows/aks-test-deploy.yaml
Labels: bug, k8s

#106 벨프(코스 Fork)기능 추가 & 기타 편의성 개선
  domain/Course/Detail/CourseHeader/index.tsx
  domain/Course/Detail/TodoItem/index.tsx
  domain/Course/Detail/TodoItem/style.ts
  domain/Course/Detail/TodoList/index.tsx
  domain/Course/Detail/TodoList/style.ts
  domain/Course/Detail/TodoTab/index.tsx
  domain/Course/SearchCourseItem/index.tsx
  domain/Course/SearchCourseItem/style.ts
Labels: new feature, modify, deployment

#109 가 오픈에서 발생한 이슈 대응
  components/LoginUser.tsx
  components/QueryStringUser.tsx
  domain/Course/BelfList/index.tsx
  domain/Course/CourseList/index.tsx
  domain/Course/CoursePinItem/index.tsx
  domain/Course/CoursePinList/index.tsx
  domain/Course/CreateCourse/index.tsx
  domain/Course/Detail/Done/DoneItem/index.tsx
  domain/Course/Detail/Done/DoneList/index.tsx
  domain/Course/Detail/TodoItem/index.tsx
  domain/Course/Detail/TodoList/index.tsx
  domain/Editer/EditImageArea/index.tsx
  domain/Editer/EditerMaster/index.tsx
  domain/Header/UserProfile/index.tsx
  domain/HomeIntro/MainIntro/style.ts
  domain/SearchInput/index.tsx
  domain/SearchInput/style.ts
  domain/Sign/SignUpForm/index.tsx
  domain/Todo/CreateTodo/index.tsx
  domain/Todo/TodayTodoItem/index.tsx
  domain/Todo/TodayTodoList/index.tsx
  domain/UserPage/UserProfile/index.tsx
  libs/oauth/index.ts
  pages/[userEmail]/[courseId]/todo/[todoId]/write/index.tsx
  states/app.ts
Labels: bug, modify

#110 up:프로그램 버전 업
  package-lock.json
  package.json
Labels: modify

#112 docker-compose를 이용한 로컬 개발환경 구성, 문서 보강, color 벨리데이션 추가
  .env.development
  Dockerfile.dev
  README.md
  docker-compose.yaml
  domain/Course/CreateCourse/index.tsx
  domain/Course/SelectCourseColor/index.tsx
  domain/Editer/EditImageArea/index.tsx
  domain/Editer/EditImageArea/style.ts
  domain/Editer/PostMaster/index.tsx
  libs/api-client.ts
  libs/colors/index.ts
  libs/course/index.ts
  libs/todo/index.ts
  libs/work-done/index.ts
  package-lock.json
  package.json
  pages/[userEmail]/[courseId]/done/[doneId]/post/index.tsx
  pages/search/index.tsx
Labels: bug, new feature, modify
