Repository belf-kr/front-server, pull requests merged in 2021-11, with the labels that each got.

#84 post API Res/Req 추가, 컴포넌트 수정, k8s 수정
  domain/Course/CoursePinList/index.tsx
  domain/Course/CreateCourse/index.tsx
  domain/Course/CreateCourse/style.ts
  domain/Course/SelectCourseColor/index.tsx
  domain/Course/SelectCourseColor/style.ts
  domain/Tag/TagInput/index.tsx
  domain/Todo/CreateTodo/index.tsx
  domain/Todo/SelectCourse/index.tsx
  domain/Todo/SelectDayOfWeek/index.tsx
  hooks/useCourseOnChange.ts
  hooks/useDayOfWeekOnChange.ts
  hooks/useGetString.ts
  hooks/useOnChange.ts
  hooks/useTagOnChange.ts
  k8s/prod.yaml
  k8s/qa.yaml
  libs/course/index.ts
  libs/todo/index.ts
  next-env.d.ts
  package-lock.json
  package.json
  pages/[userId]/index.tsx
  types/components-type/todo/index.ts
Labels: deployment

#86 로그인 기능 추가
  .env.development
  .env.prod
  .env.qa
  components/AppInit.tsx
  domain/Header/index.tsx
  domain/Sign/SignInForm/index.tsx
  domain/Sign/SignUpForm/index.tsx
  domain/ThemeChangeButton/index.tsx
  domain/UserPage/UserProfile/index.tsx
  libs/api-client.ts
  libs/colors/index.ts
  libs/course/index.ts
  libs/oauth/index.ts
  libs/todo/index.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/auth-end.tsx
  pages/index.tsx
  states/app.ts
  states/themeState.ts
  theme/ThemeRoot.tsx
Labels: new feature

#87 v0.6.0
  .env.development
  .env.prod
  .env.qa
  components/AppInit.tsx
  domain/Header/index.tsx
  domain/Sign/SignInForm/index.tsx
  domain/Sign/SignUpForm/index.tsx
  domain/ThemeChangeButton/index.tsx
  domain/UserPage/UserProfile/index.tsx
  libs/api-client.ts
  libs/colors/index.ts
  libs/course/index.ts
  libs/oauth/index.ts
  libs/todo/index.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/auth-end.tsx
  pages/index.tsx
  states/app.ts
  states/themeState.ts
  theme/ThemeRoot.tsx
Labels: new feature

#88 기존 API Req/Res 인증 서버 연동 & useEffect 언마운트 경고 해결
  domain/Course/CourseList/index.tsx
  domain/Todo/SelectCourse/index.tsx
  libs/course/index.ts
  libs/todo/index.ts
Labels: bug, modify

#89 서비스에 가입된 사용자 대쉬보드 확인 및 오늘 할일 쿼리 수정
  domain/Course/CourseList/index.tsx
  domain/Course/CreateCourse/index.tsx
  domain/Todo/CreateTodo/index.tsx
  domain/Todo/TodayTodoList/index.tsx
  domain/UserPage/UserPageNavigate/index.tsx
  domain/UserPage/UserProfile/index.tsx
  libs/oauth/index.ts
  libs/todo/index.ts
  package-lock.json
  pages/[userEmail]/index.tsx
  pages/[userId]/index.tsx
  pages/auth-end.tsx
  states/app.ts
Labels: new feature

#90 코스 디테일 페이지 기능 및 API 연동
  components/UserCheck.tsx
  domain/Course/CourseList/index.tsx
  domain/Course/CoursePinItem/index.tsx
  domain/Course/CoursePinList/index.tsx
  domain/Course/Detail/ChoiceDate/index.tsx
  domain/Course/Detail/ChoiceDate/style.ts
  domain/Course/Detail/CourseDetailNavigate/index.tsx
  domain/Course/Detail/CourseDetailNavigate/style.ts
  domain/Course/Detail/CourseHeader/index.tsx
  domain/Course/Detail/CourseHeader/style.ts
  domain/Course/Detail/ExplanationTextArea/index.tsx
  domain/Course/Detail/ExplanationTextArea/style.ts
  domain/Course/Detail/TodoItem/index.tsx
  domain/Course/Detail/TodoItem/style.ts
  domain/Course/Detail/TodoList/index.tsx
  domain/Course/Detail/TodoList/style.ts
  domain/Course/Detail/TodoTab/index.tsx
  domain/Todo/SelectCourse/index.tsx
  hooks/useGetDate.ts
  icons/CheckIcon/index.tsx
  icons/svg/Check.svg
  layouts/DetailLayout/index.tsx
  layouts/DetailLayout/style.ts
  libs/course/index.ts
  libs/todo/index.ts
  package-lock.json
  package.json
  pages/[userEmail]/[courseId]/index.tsx
  pages/[userEmail]/index.tsx
  pages/new-todo/index.tsx
Labels: new feature, modify, deployment

#92 Belf 비회원 초기화면
  components/AppInit.tsx
  domain/HomeIntro/MainIntro/index.tsx
  domain/HomeIntro/MainIntro/style.ts
  icons/svg/Children.svg
  icons/svg/Field.svg
  k8s/prod.yaml
  k8s/qa.yaml
  layouts/RootLayout/index.tsx
  layouts/RootLayout/style.ts
  package-lock.json
  package.json
  pages/api/ping.ts
  pages/index.tsx
  theme/GlobalStyle.ts
Labels: new feature, modify, deployment

#93 한일 작성 기능 추가, 파일 서버 연동 확인, 스케일 업, k8s 헬스 체크 추가 (*추가 코드 정리 및 기능 개선 필요)
  domain/Editer/EditImageArea/index.tsx
  domain/Editer/EditImageArea/style.ts
  domain/Editer/EditTextArea/index.tsx
  domain/Editer/EditTextArea/style.ts
  domain/Editer/EditerMaster/index.tsx
  domain/Editer/EditerMaster/style.ts
  domain/Editer/WriteNodeItem/index.tsx
  domain/Editer/WriteNodeItem/style.ts
  domain/Editer/WriteNodeList/index.tsx
  domain/Editer/WriteNodeList/style.ts
  icons/AddIcon/index.tsx
  icons/ImageIcon/index.tsx
  icons/TextIcon/index.tsx
  icons/svg/Add.svg
  icons/svg/Image.svg
  icons/svg/Text.svg
  k8s/prod.yaml
  k8s/qa.yaml
  layouts/PostWorkDoneLayout/index.tsx
  layouts/PostWorkDoneLayout/style.ts
  pages/[userEmail]/[courseId]/[todoId]/post-work-done/index.tsx
  types/components-type/editer/index.ts
Labels: new feature, modify, deployment, k8s

#94 한일 작성 기능 추가, 파일 서버 연동 확인
  .env.development
  .env.prod
  .env.qa
  domain/Course/Detail/TodoItem/index.tsx
  domain/Editer/EditImageArea/index.tsx
  domain/Editer/EditImageArea/style.ts
  domain/Editer/EditerMaster/index.tsx
  domain/Editer/EditerMaster/style.ts
  domain/Editer/WriteNodeList/index.tsx
  domain/Todo/TodayTodoItem/index.tsx
  domain/Todo/TodayTodoList/index.tsx
  hooks/useGetEditNodeList.ts
  libs/api-client.ts
  libs/storage/index.ts
  libs/todo/index.ts
  libs/work-done/index.ts
  pages/[userEmail]/[courseId]/[todoId]/post-work-done/index.tsx
Labels: new feature, modify, deployment
